spring:
  datasource:
    url: jdbc:mysql://eatup.cf0vbyqqnwag.ap-northeast-2.rds.amazonaws.com:3306/gorany?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: eatup
    password: eatup1234
    
  thymeleaf:
    cache: false

    
  servlet:
    multipart:
      max-file-size: 20971520
      max-request-size: 41943040
      file-size-threshold: 20971520
      
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: chu1070y@gmail.com
    password: gorany2018
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml  
  

logging:
  level:
    org.hibernate: debug
    org.springframework: info
    org.salem: debug
